const ADD_PRINCIPLE = 'ADD_PRINCIPLE';
const DELETE_PRINCIPLE_BY_ID = 'DELETE_PRINCIPLE_BY_ID';
const UPDATE_PRINCIPLE_BY_ID = 'UPDATE_PRINCIPLE_BY_ID';

export { ADD_PRINCIPLE, DELETE_PRINCIPLE_BY_ID, UPDATE_PRINCIPLE_BY_ID };
